T/letsencrypt haproxy (#1053)
* Update: disable SSL deploy

* Update: finish renewal process for letsencrypt/haproxy

 * make ssl dir configurable and inject
 * append certs into a combined file
 * reload haproxy afterwards

Related: DEVOPS-163

* Update: test cases

 * for ssl_dir
 * for etc_dir (see bug fixed in #1052

Related: DEVOPS-163

* Fix: re-add missing dependency for vagrant

* Update: consolidate setup

 * ensure we don't duplicate command logic in setup and renewal
 * since all recipes are executed initially, we will have be able to retrieve initial certs

Related: DEVOPS-163

* Refactor: renewal script

 * wrap renewal/setup code in function
 * be a little more verbose with messaging from cron
 * ensure we can actually initially setup certs
 * update documentation

Related: DEVOPS-163

* Update: run let's encrypt before we install haproxy for initial setup

(This may imply that we cannot reload haproxy on the first run because
it is not yet there. But I will have to try this later.) :shipit:

Related: DEVOPS-163

* Update: make setup process more reciliant

 * document limitations
 * allow initial setup to fail in case dependencies are missing

Related: DEVOPS-163

* Refactor: move ssl config into a partial

* Fix: also subscribe to let's encrypt

Related: DEVOPS-163

* Fix: CS (re-apply)

* Refactor: ssl tests

 * unify mock on command
 * test ssl disabled also

Related: DEVOPS-163

* Fix: re-configure order so haproxy can subscribe

Related: DEVOPS-163

* Update: ensure we can start haproxy when the PEM is missing

Related: DEVOPS-163

* Update: execute twice

* Enhancement: LWRP to create self-sigend certificates

Related: DEVOPS-163

* Refactor: input validation in easybib_sslcertificate

Related: DEVOPS-163

* Refactor: support filenames

 * consolidate checking input (e.g. is this really a path or actual)
 * push chomp chomp into new method

Related: DEVOPS-163

* Update: test self-signing and remove hardcoded SSL data

Related: DEVOPS-163

* Fix: cs cs

* Refactor: always have a certificate

 * objective is to always have a cert in place so haproxy can start
 * defeats the chicken-egg problem
 * actual SSL certs will be deployed or let's encrypted later

Related: DEVOPS-163

* Fix: update tests

 * remove stubs
 * remove test

* Move of the is_letsencrypt acl to above the SSL Redirect action
Change of the SSL redirect action to not do if is letsencrypt

* make is_letsencrypt acl ALWAYS appear otherwise non-ssl haproxy setup will fail

diff --git a/ies-letsencrypt/templates/default/certbot-cronjob.sh.erb b/ies-letsencrypt/templates/default/certbot-cronjob.sh.erb
--- a/ies-letsencrypt/templates/default/certbot-cronjob.sh.erb
+++ b/ies-letsencrypt/templates/default/certbot-cronjob.sh.erb
@@ -5,16 +5,31 @@ config_file="$etc/cli.ini"
 limit=30
 
 DOMAIN=`grep "^\s*domains" $config_file | sed "s/^\s*domains\s*=\s*//" | sed 's/(\s*)\|,.*$//'`
-echo $DOMAIN
+if [ -z "$DOMAIN" ] ; then
+  echo "[ERROR] no domain found"
+  exit 1;
+fi
 
-COMBINED="/etc/nginx/ssl/cert.combined.pem"
+COMBINED="<%=@ssl_dir%>/cert.combined.pem"
 
 CERT_FILE="$etc/live/$DOMAIN/fullchain.pem"
 KEY_FILE="$etc/live/$DOMAIN/privkey.pem"
 
+function get_cert {
+  <%=@certbot_bin%> <%=@opts.join(' ')%>
+  if [ $? -ne 0 ] ; then
+    echo "[ERROR] certbot-auto failed."
+    exit 1;
+  fi
+
+  cat $CERT_FILE $KEY_FILE > $COMBINED
+  service haproxy reload
+}
+
 if [ ! -f $CERT_FILE ]; then
-  echo "[ERROR] certificate file not found for domain $domain."
-  exit 1;
+  echo "[INFO] certificate file not found for domain $DOMAIN."
+  get_cert
+  exit 0;
 fi
 
 EXP=$(date -d "`openssl x509 -in $CERT_FILE -text -noout|grep "Not After"|cut -c 25-`" +%s)
@@ -22,12 +37,10 @@ NOW=$(date -d "now" +%s)
 DAYS=$(echo \( $EXP - $NOW \) / 86400 |bc)
 
 if [ "$EXP" -gt "$limit" ] ; then
-  echo "The certificate is up to date, no need for renewal ($DAYS days left)."
+  echo "[DEBUG] The certificate is up to date, no need for renewal ($DAYS days left)."
   exit 0;
 fi
 
-<%=@certbot_bin%> <%=@opts.join(' ')%>
+echo "[INFO] $EXP left, we'll attempt to renew."
 
-# todo
-# 1. combine cert: sudo bash -c "cat $CERT_FILE $KEY_FILE > $COMBINED"
-# 2. reload haproxy: service haproxy reload
+get_cert
